export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const OPEN_ALERT = 'OPEN_ALERT';
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_ALERT = 'CLOSE_ALERT';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const SET_ALERT_TYPE = 'SET_ALERT_TYPE';

export const SET_TASK_DATA = 'SET_TASK_DATA';
export const CLEAR_TASK_DATA = 'CLEAR_TASK_DATA';
export const SET_TASK_NAME = 'SET_TASK_NAME';
export const SET_MIN_PERIOD = 'SET_MIN_PERIOD';
export const SET_PASS_CRITERIA = 'SET_PASS_CRITERIA';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_TABLE_NAME = 'SET_TABLE_NAME';

export const SET_ORIGINAL_DATA = 'SET_ORIGINAL_DATA';
export const SET_SCHEMA_NAME = 'SET_SCHEMA_NAME';
export const CLEAR_ORIGINAL_DATA = 'CLEAR_ORIGINAL_DATA';
export const SET_COLUMNS = 'SET_COLUMNS';
